name: Run bot

on:
  push:
    schedule:
      - cron: '0 */5 * * *'


jobs:
  build-and-run:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      # - run: node --version
      # - run: npm --version
      # - uses: actions/checkout@v3
      # - run: npm i discord.js dotenv openai
      # - run: node index.js
      #   env:
      #     CI: true
      #     OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      #     BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    - name: Build node and npm
      id: build-node
      run: node --version
      run: npm --version
      uses: actions/checkout@v3
      run: npm i discord.js dotenv openai

    - name: Run bot
      id: run-bot
      run: node index.js
      env:
        CI: true
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    
    - name: Rerun
      if: failure() && steps.run-bot.outcome != 'success'
      uses: https://github.com/Hohshua/Discord-ChatGPT-Bot/blob/main/.github/workflows/build.yml@main