on: 
  push:
    schedule:
      # - cron: '0,5,10,15,20 * * * *'
      - cron: '0 */6 * * *'
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm i discord.js dotenv openai
      - run: node index.js
        env:
          CI: true
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
