name: Run bot

on:
  push:
    schedule:
      - cron: '0 */5 * * *'
  workflow_call:
    secrets:
      OPENAI_KEY:
        required: true
      BOT_TOKEN:
        required: true


jobs:
  build-and-run:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      # - run: node --version
      # - run: npm --version
      # - uses: actions/checkout@v3
      # - run: npm i discord.js dotenv openai
      # - run: node index.js
      #   env:
      #     CI: true
      #     OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      #     BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    - name: Build node and npm
      id: build-node
      run: |
        node --version
        npm --version

    - name: Actions checkout
      id: actions-checkout
      uses: actions/checkout@v3

    - name: Run bot
      id: run-bot
      env:
        CI: true
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        npm i discord.js dotenv openai
        node index.js
    
    - name: Rerun
      if: failure() && steps.run-bot.outcome != 'success'
      uses: ./.github/workflows/build.yml@main
