on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
  install-packages:
    steps:
      - run: npm i discord.js dotenv openai
  run-bot:
    steps:
      - run: node index.js
        env:
          CI: true
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}